env:
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2021
  requireConfigFile: false
  babelOptions:
    plugins:
      - '@babel/syntax-top-level-await'
      - '@babel/syntax-import-assertions'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-constant-condition:
    - off
globals:
  bot: true
