env:
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parser: @babel/eslint-parser
parserOptions:
  sourceType: module
  ecmaVersion: 2021
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
globals:
  bot: true
